"""game scores

Revision ID: 5caa54b67a2e
Revises: 
Create Date: 2026-05-13 11:58:01.304033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5caa54b67a2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamescore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('puntuacion_total', sa.Integer(), nullable=False),
    sa.Column('mejor_racha', sa.Integer(), nullable=False),
    sa.Column('partidas_jugadas', sa.Integer(), nullable=False),
    sa.Column('partidas_ganadas', sa.Integer(), nullable=False),
    sa.Column('mejor_puntuacion', sa.Integer(), nullable=False),
    sa.Column('mejor_movimientos_facil', sa.Integer(), nullable=False),
    sa.Column('mejor_movimientos_medio', sa.Integer(), nullable=False),
    sa.Column('mejor_movimientos_dificil', sa.Integer(), nullable=False),
    sa.Column('mejor_mov_facil', sa.Integer(), nullable=False),
    sa.Column('mejor_mov_dificil', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamescore')
    # ### end Alembic commands ###
